// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:deepfilternet/src/df_bindings_generated.dart')
library;

import 'dart:ffi' as ffi;

/// Create a DeepFilterNet Model
///
/// Args:
/// - path: File path to a DeepFilterNet tar.gz onnx model
/// - atten_lim: Attenuation limit in dB.
///
/// Returns:
/// - DF state doing the full processing: stft, DNN noise reduction, istft.
@ffi.Native<ffi.Pointer<DFState> Function(ffi.Pointer<ffi.Char>, ffi.Float, ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<DFState> df_create(
  ffi.Pointer<ffi.Char> path,
  double atten_lim,
  ffi.Pointer<ffi.Char> log_level,
);

/// Get DeepFilterNet frame size in samples.
@ffi.Native<ffi.UintPtr Function(ffi.Pointer<DFState>)>()
external int df_get_frame_length(
  ffi.Pointer<DFState> st,
);

/// Get the next log message. Must be freed via `df_free_log_msg(ptr)`
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<DFState>)>()
external ffi.Pointer<ffi.Char> df_next_log_msg(
  ffi.Pointer<DFState> st,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>()
external void df_free_log_msg(
  ffi.Pointer<ffi.Char> ptr,
);

/// Set DeepFilterNet attenuation limit.
///
/// Args:
/// - lim_db: New attenuation limit in dB.
@ffi.Native<ffi.Void Function(ffi.Pointer<DFState>, ffi.Float)>()
external void df_set_atten_lim(
  ffi.Pointer<DFState> st,
  double lim_db,
);

/// Set DeepFilterNet post filter beta. A beta of 0 disables the post filter.
///
/// Args:
/// - beta: Post filter attenuation. Suitable range between 0.05 and 0;
@ffi.Native<ffi.Void Function(ffi.Pointer<DFState>, ffi.Float)>()
external void df_set_post_filter_beta(
  ffi.Pointer<DFState> st,
  double beta,
);

/// Processes a chunk of samples.
///
/// Args:
/// - df_state: Created via df_create()
/// - input: Input buffer of length df_get_frame_length()
/// - output: Output buffer of length df_get_frame_length()
///
/// Returns:
/// - Local SNR of the current frame.
@ffi.Native<ffi.Float Function(ffi.Pointer<DFState>, ffi.Pointer<ffi.Float>, ffi.Pointer<ffi.Float>)>()
external double df_process_frame(
  ffi.Pointer<DFState> st,
  ffi.Pointer<ffi.Float> input,
  ffi.Pointer<ffi.Float> output,
);

/// Processes a filter bank sample and return raw gains and DF coefs.
///
/// Args:
/// - df_state: Created via df_create()
/// - input: Spectrum of shape `[n_freqs, 2]`.
/// - out_gains_p: Output buffer of real-valued ERB gains of shape `[nb_erb]`. This function
/// may set this pointer to NULL if the local SNR is greater 30 dB. No gains need to be
/// applied then.
/// - out_coefs_p: Output buffer of complex-valued DF coefs of shape `[df_order, nb_df_freqs, 2]`.
/// This function may set this pointer to NULL if the local SNR is greater 20 dB. No DF
/// coefficients need to be applied.
///
/// Returns:
/// - Local SNR of the current frame.
@ffi.Native<
  ffi.Float Function(
    ffi.Pointer<DFState>,
    ffi.Pointer<ffi.Float>,
    ffi.Pointer<ffi.Pointer<ffi.Float>>,
    ffi.Pointer<ffi.Pointer<ffi.Float>>,
  )
>()
external double df_process_frame_raw(
  ffi.Pointer<DFState> st,
  ffi.Pointer<ffi.Float> input,
  ffi.Pointer<ffi.Pointer<ffi.Float>> out_gains_p,
  ffi.Pointer<ffi.Pointer<ffi.Float>> out_coefs_p,
);

/// Free a DeepFilterNet Model
@ffi.Native<ffi.Void Function(ffi.Pointer<DFState>)>()
external void df_free(
  ffi.Pointer<DFState> model,
);

final class DFState extends ffi.Opaque {}
